### ISSUE TITLE
Add constraint component attribute to SANodes

### ISSUE THREAD

**Issue by lucascool12** [MaximeJakubowski/sls_project#3]
Currently when using a SANode it is not possible to track down which constraint component would correspond with a SANode.

I suggest adding an attribute called constraintComponent which will hold the SHACL constraint component if any which corresponds with this SANode.

**Comment by MaximeJakubowski** [comment]
That is right. It would be nice to integrate this in the library. This involves adding information about the original shapes graph into the datastructure. It is not clear to me how to approach this properly. I will look into this a little more during the coming two weeks.

**Comment by lucascool12** [comment]
I opened draft pull request #4 containing the changes I made to add constraint components to SANodes (I'm not sure it works in every case), it contains a breaking change for TEST Op.
