### ISSUE TITLE
class targets do not adhere to SHACL instance definition

### ISSUE THREAD

**Issue by lucascool12** [MaximeJakubowski/sls_project#9]
Currently when parsing a shapes graph that has a shape that targets a class, the generated SANode does not adhere to the definition of an SHACL instance.
See test: [targetClassImplicit-001.ttl](https://github.com/w3c/data-shapes/blob/6f9248970f4081c23e99d4d599b441d690f5403a/data-shapes-test-suite/tests/core/targets/targetClassImplicit-001.ttl).
The target for this shapes graph is:
```
http://datashapes.org/sh/tests/core/targets/targetClassImplicit-001.test#SuperClass 
(Op.OR  cc=None  
 (Op.COUNTRANGE  cc=None  rdflib.term.Literal('1', datatype=rdflib.term.URIRef('http://www.w3.org/2001/XMLSchema#integer'))
  None
  
  (POp.PROP  rdflib.term.URIRef('http://www.w3.org/1999/02/22-rdf-syntax-ns#type'))
  
  (Op.HASVALUE  cc=None  rdflib.term.URIRef('http://datashapes.org/sh/tests/core/targets/targetClassImplicit-001.test#SuperClass'))))

```
As you can see the generated SANode for ex:SuperClass does not target instances of the class ex:SubClass.
The same occurs if we use sh:targetClass instead of implicit class targets.

**Comment by MaximeJakubowski** [comment]
Thanks, yes, this is true. What should happen with the targeting shape is that it also covers subclasses. Just like the slsparser does with sh:class. Do you agree?

Also, I think the slsparser plainly does not support implicit class targets. This should still be added.

**Comment by lucascool12** [comment]
> Thanks, yes, this is true. What should happen with the targeting shape is that it also covers subclasses. Just like the slsparser does with sh:class. Do you agree?

Yes I think it should do the same thing as what happens with sh:class.

> Also, I think the slsparser plainly does not support implicit class targets. This should still be added.

For the example above changing from implicit class targets to explicit does not change the SANode produced for this shape. So it seems it is implemented.
